package io.github.tobyrue.rtc;

import javax.tools.*;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.OutputStream;
import java.lang.reflect.*;
import java.net.URI;
import java.security.SecureClassLoader;
import java.util.*;
import java.util.stream.Collectors;

/**
 * <p><i>RTC v1.0.1 (c) Trin Wasinger 2026</i></p>
 * A utility for compiling and running Java code from strings at runtime. Requires JDK installation.
 *
 * @version {@value RTC#VERSION}
 * @author Trin Wasinger
 */
@SuppressWarnings("unused")
public final class RTC {
    private static final String VERSION = "1.0.1";

    /**
     * Wrapper class for any errors generated by compiling or invoking code
     */
    public static final class RTCException extends Exception {
        private RTCException(final String message) {
            super(message);
        }

        private RTCException(final Throwable cause) {
            super(cause);
        }

        private RTCException(final Throwable cause, final String message) {
            super(message, cause);
        }

        private RTCException(final String message, final Object... args) {
            this(String.format(message, args));
        }

        private RTCException(final Throwable cause, final String message, final Object... args) {
            this(cause, String.format(message, args));
        }
    }

    /**
     * An interface to represent functions in newly compiled code
     */
    @FunctionalInterface
    public interface Function {
        /**
         * Calls the underlying function
         *
         * @param args the args to pass
         * @return the return value of the underlying method
         * @throws RTCException if an error occurred invoking the underlying function
         */
        Object run(final Object... args) throws RTCException;
    }

    /**
     * Compiles string sourcecode
     *
     * @param text the source code to compile
     * @return an {@link Environment} to access the compiled code via
     * @throws RTCException if an unexpected error occurred
     */
    public static Environment compile(final String text) throws RTCException {
        if (ToolProvider.getSystemJavaCompiler() instanceof final JavaCompiler compiler) {
            try (final JavaFileManager fileManager = new ForwardingJavaFileManager<JavaFileManager>(compiler.getStandardFileManager(null, null, null)) {
                final private Map<String, ByteArrayOutputStream> streams = new HashMap<>();

                @Override
                public ClassLoader getClassLoader(final Location location) {
                    return new SecureClassLoader() {
                        @Override
                        protected Class<?> findClass(final String name) throws ClassNotFoundException {
                            if (streams.get(name) instanceof final ByteArrayOutputStream stream) {
                                final byte[] bytes = stream.toByteArray();
                                return super.defineClass(name, bytes, 0, bytes.length);
                            }
                            throw new ClassNotFoundException(name);
                        }
                    };
                }

                @Override
                public JavaFileObject getJavaFileForOutput(final Location location, final String className, final JavaFileObject.Kind kind, final FileObject sibling) throws IOException {
                    return new SimpleJavaFileObject(URI.create("text:///" + className.replace('.', '/') + kind.extension), kind) {
                        @Override
                        public OutputStream openOutputStream() throws IOException {
                            return streams.computeIfAbsent(className, k -> new ByteArrayOutputStream());
                        }
                    };
                }
            }) {
                final DiagnosticCollector<JavaFileObject> diagnostics = new DiagnosticCollector<>();

                final boolean success = compiler.getTask(null, fileManager, diagnostics, List.of("-classpath", System.getProperty("java.class.path")), null, List.of(new SimpleJavaFileObject(URI.create("text:///anonymous" + JavaFileObject.Kind.SOURCE.extension), JavaFileObject.Kind.SOURCE) {
                    @Override
                    public CharSequence getCharContent(final boolean ignoreEncodingErrors) {
                        return text;
                    }
                })).call();

                if (success) {
                    return new Environment(fileManager.getClassLoader(null));
                } else {
                    throw new RTCException("Compile Error\n\n" + diagnostics.getDiagnostics().stream().map(String::valueOf).collect(Collectors.joining("\n")));
                }
            } catch(final IOException e) {
                throw new RTCException("Unable to open file manager", e);
            }
        } else {
            throw new RTCException("No JDK compiler found");
        }
    }

    /**
     * Gets the underlying Java version
     * @return the version
     */
    public static String getJavaVersion() {
        return "Java v" + Runtime.version().toString();
    }

    /**
     * Gets the RTC version
     * @return the version
     */
    public static String getVersion() {
        return "RTC v" + RTC.VERSION;
    }

    /**
     * Checks if there is a JDK compiler available
     * @return <code>true</code> if the compiler can be found
     */
    public static boolean hasJDKCompiler() {
        return ToolProvider.getSystemJavaCompiler() != null;
    }

    /**
     * A context to access  the results of a compilation
     *
     * @implNote Some of these methods may still work if called on a different Environment,
     * but you are advised not to try that because of {@link ClassLoader} issues.
     */
    public static final class Environment {
        private final ClassLoader classLoader;

        private Environment(final ClassLoader classLoader) {
            this.classLoader = classLoader;
        }

        /**
         * Locates a newly compiled class
         *
         * @param name the name of the class
         * @return the class
         * @throws RTCException if not found
         */
        public Class<?> findClass(final String name) throws RTCException {
            try {
                return Class.forName(name, true, this.classLoader);
            } catch (final ClassNotFoundException e) {
                throw new RTCException(e, "Unable to locate class '%s'", name);
            }
        }

        /**
         * Gets a given function from newly compiled code
         *
         * @apiNote <code>target</code> should take the form <code>"com.mypackage.MyClass.foo"</code> where <code>com.mypackage.MyClass</code> is a class
         * and <code>foo</code> is a public static function with no overloads.
         *
         * @param target the function to find
         * @return a {@link RTC.Function} representing the function
         * @throws RTCException if the function does not exist or is inaccessible
         */
        public RTC.Function getFunction(final String target) throws RTCException {
            final String name = target.substring(target.lastIndexOf('.' ) + 1);
            return Arrays.stream(this.findClass(target.substring(0, target.lastIndexOf('.' ))).getDeclaredMethods())
                    .filter(method -> method.getName().equals(name) && Modifier.isPublic(method.getModifiers())&& Modifier.isStatic(method.getModifiers()))
                    .limit(1)
                    .map(method -> {
                        try {
                            method.setAccessible(true);
                            return List.of((RTC.Function) (args) -> {
                                try {
                                    return method.invoke(null, args);
                                } catch (final IllegalAccessException | InvocationTargetException | IllegalArgumentException e) {
                                    e.printStackTrace();
                                    throw new RTCException(e, "Unable to invoke method '%s'", name);
                                }
                            });
                        } catch (InaccessibleObjectException | SecurityException e) {
                            return Collections.<RTC.Function>emptyList();
                        }
                    })
                    .flatMap(List::stream)
                    .findFirst()
                    .orElseThrow(() -> new RTCException("Unable to locate accessible method '%s'", name));
        }

        /**
         * Gets the value of a variable in a newly compiled class
         *
         * @apiNote <code>target</code> should take the form <code>"com.mypackage.MyClass.foo"</code> where <code>com.mypackage.MyClass</code> is a class
         * and <code>foo</code> is a public static variable.
         *
         * @param target the variable to get
         * @return the value of the variable
         * @throws RTCException if the variable does not exist or is inaccessible
         */
        public Object getValue(final String target) throws RTCException {
            final String name = target.substring(target.lastIndexOf('.' ) + 1);
            try {
                final Field field = this.findClass(target.substring(0, target.lastIndexOf('.' ))).getDeclaredField(name);
                if (Modifier.isPublic(field.getModifiers()) && Modifier.isStatic(field.getModifiers())) {
                    field.setAccessible(true);
                    return field.get(null);
                }
            } catch (final IllegalAccessException e) {
                throw new RTCException(e, "Unable to access field '%s'", name);
            } catch (final InaccessibleObjectException | SecurityException | NoSuchFieldException ignored) {

            }
            throw new RTCException("Unable to locate accessible field '%s'", name);
        }

        /**
         * Modifies the value of a variable in a newly compiled class
         *
         * @apiNote <code>target</code> should take the form <code>"com.mypackage.MyClass.foo"</code> where <code>com.mypackage.MyClass</code> is a class
         * and <code>foo</code> is a public static non-final variable.
         *
         * @param target the variable to get
         * @param value the new value
         * @throws RTCException if the variable does not exist, is inaccessible, or cannot be modified
         */
        public void setValue(final String target, final Object value) throws RTCException {
            final String name = target.substring(target.lastIndexOf('.' ) + 1);
            try {
                final Field field = this.findClass(target.substring(0, target.lastIndexOf('.'))).getDeclaredField(name);
                if (Modifier.isFinal(field.getModifiers())) {
                    throw new RTCException("Unable to modify final field '%s'", name);
                }

                if (Modifier.isPublic(field.getModifiers()) && Modifier.isStatic(field.getModifiers())) {
                    field.setAccessible(true);
                    field.set(null, value);
                    return;
                }
            } catch (final IllegalArgumentException e) {
                throw new RTCException(e, "Cannot assign value '%s' to field '%s'", value, name);
            } catch (final IllegalAccessException e) {
                throw new RTCException(e, "Unable to access field '%s'", name);
            } catch (final InaccessibleObjectException | SecurityException | NoSuchFieldException ignored) {

            }
            throw new RTCException("Unable to locate accessible field '%s'", name);
        }

        /**
         * Creates an instance of a newly compiled class
         *
         * @apiNote <code>target</code> should take the form <code>"com.mypackage.MyClass"</code> where <code>com.mypackage.MyClass</code> is a class
         * with a single public constructor.
         *
         * @param target the class to construct
         * @param args the args to pass
         * @return the new instance
         * @throws RTCException if the constructor is inaccessible or cannot be invoked
         */
        public Object create(final String target, final Object... args) throws RTCException {
            try {
                return Arrays.stream(this.findClass(target).getDeclaredConstructors())
                        .filter(constructor -> Modifier.isPublic(constructor.getModifiers()))
                        .limit(1)
                        .map(constructor -> {
                            try {
                                constructor.setAccessible(true);
                                return List.of(constructor);
                            } catch (InaccessibleObjectException | SecurityException e) {
                                return Collections.<Constructor<?>>emptyList();
                            }
                        }).flatMap(List::stream).findFirst().orElseThrow(() -> new RTCException("Unable to locate accessible constructor for '%s")).newInstance(args);
            } catch (final IllegalAccessException | InvocationTargetException | IllegalArgumentException | InstantiationException | ExceptionInInitializerError e) {
                throw new RTCException(e, "Unable to invoke constructor for '%s'", target);
            }
        }
    }

    /**
     * Compiles string sourcecode and invokes the given newly created function
     *
     * @apiNote <code>target</code> should take the form <code>"com.mypackage.MyClass.foo"</code> where <code>com.mypackage.MyClass</code> is a class
     * and <code>foo</code> is a public static function with no overloads.
     *
     * @param text the source code to compile
     * @param target the function to call
     * @param args the arguments to invoke the function with
     * @return the return value of the function
     * @throws RTCException if an error occurred
     */
    public static Object run(final String text, final String target, final Object... args) throws RTCException {
        return RTC.compile(text).getFunction(target).run(args);
    }

    /**
     * Stringifies <code>args</code> and prints to stdout
     *
     * @param args the values to print
     */
    public static void println(final Object... args) {
        System.out.printf(Arrays.stream(args).map(String::valueOf).collect(Collectors.joining()) + "\n");
    }

    /**
     * Stringifies <code>args</code> and prints to stderr
     *
     * @param args the values to print
     */
    public static void eprintln(final Object... args) {
        System.err.printf(Arrays.stream(args).map(String::valueOf).collect(Collectors.joining()) + "\n");
    }
}
